/* ---------- Configuration Ship of Harkinian ----------
   Options et astuces de logique du randomizer de Ship of Harkinian 9.2.3 « Ackbar Delta »
   (settings.cpp au commit cb71e22, celui des spoilers de l'utilisateur). Seules les options qui changent
   la logique, les checks ou les objets suivis sont reprises (voir SPEC.md > Configuration) ; les autres sont
   listées dans SETTINGS_IGNORED pour que l'import d'un spoiler les passe sans les signaler.
   Valeurs stockées = chaînes SoH exactes (ex. 'Deku Only') : l'import est direct, l'affichage traduit.
   Fichier généré à partir des sources SoH, puis maintenu à la main. */
const CONFIG_TABS = [
  { id:'logic', label:'Logique & accès', cards:[['logic','Logique'], ['access','Accès aux zones'], ['wincon','Pont et Ganon'], ['skips','Raccourcis']] },
  { id:'entrances', label:'Entrées', cards:[['shuffle','Entrées mélangées'], ['oneway','Sens unique'], ['pools','Pools']] },
  { id:'dungeons', label:'Donjons', cards:[['items','Objets de donjon'], ['rewards','Récompenses'], ['keyrings','Trousseaux de clés'], ['mq','Master Quest']] },
  { id:'shuffles', label:'Mélanges', cards:[['locations','Lieux'], ['items','Objets'], ['abilities','Capacités et langues'], ['extras','Objets additionnels']] },
  { id:'starting', label:'Départ', hidden:true, cards:[['equipment','Équipement et objets'], ['songs','Chants']] },
  { id:'tricks', label:'Astuces' },
  { id:'router', label:'Routeur' },
];

// { key, soh (nom exact SoH), label, card ('onglet.carte'), type 'choice'|'number', choices [[valeur SoH, libellé]],
//   min/max/step, def (valeur par défaut SoH), show(s) (visibilité, reprise des Hide()/Unhide() de SoH) }
const SETTINGS_DEF = [
  { key:"logic", soh:"Logic", label:"Logique", card:"logic.logic", type:'choice', choices:[["Glitchless","Sans bug"],["No Logic","Sans logique"]], def:"Glitchless" },
  { key:"gsExpectSunsSong", soh:"Night Skulltula's Expect Sun's Song", label:"Skulltulas de nuit : Chant du Soleil requis", card:"logic.logic", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingAge", soh:"Starting Age", label:"Âge de départ", card:"logic.logic", type:'choice', choices:[["Child","Enfant"],["Adult","Adulte"],["Random","Aléatoire"]], def:"Child" },
  { key:"selectedStartingAge", soh:"Selected Starting Age", label:"Âge tiré", card:"logic.logic", type:'choice', choices:[["Child","Enfant"],["Adult","Adulte"]], def:"Child", show:s => s.startingAge === 'Random' },
  { key:"closedForest", soh:"Closed Forest", label:"Forêt Kokiri", card:"logic.access", type:'choice', choices:[["On","Fermée"],["Deku Only","Arbre Mojo seul"],["Off","Ouverte"]], def:"On" },
  { key:"kakarikoGate", soh:"Kakariko Gate", label:"Portail de Cocorico", card:"logic.access", type:'choice', choices:[["Closed","Fermé"],["Open","Ouvert"]], def:"Closed" },
  { key:"doorOfTime", soh:"Door of Time", label:"Porte du Temps", card:"logic.access", type:'choice', choices:[["Closed","Fermée"],["Song only","Chant seul"],["Open","Ouverte"]], def:"Closed" },
  { key:"zorasFountain", soh:"Zora's Fountain", label:"Fontaine Zora", card:"logic.access", type:'choice', choices:[["Closed","Fermée"],["Closed as child","Fermée (enfant)"],["Open","Ouverte"]], def:"Closed" },
  { key:"sleepingWaterfall", soh:"Sleeping Waterfall", label:"Cascade du Domaine Zora", card:"logic.access", type:'choice', choices:[["Closed","Fermée"],["Open","Ouverte"]], def:"Closed" },
  { key:"jabuJabu", soh:"Jabu-Jabu", label:"Jabu-Jabu", card:"logic.access", type:'choice', choices:[["Closed","Fermé"],["Open","Ouvert"]], def:"Closed" },
  { key:"lockOverworldDoors", soh:"Lock Overworld Doors", label:"Portes de l'overworld verrouillées", card:"logic.access", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"fortressCarpenters", soh:"Fortress Carpenters", label:"Charpentiers de la Forteresse", card:"logic.access", type:'choice', choices:[["Normal","Normal (4)"],["Fast","Rapide (1)"],["Free","Libres"]], def:"Normal" },
  { key:"rainbowBridge", soh:"Rainbow Bridge", label:"Pont arc-en-ciel", card:"logic.wincon", type:'choice', choices:[["Vanilla","Vanilla"],["Always open","Ouvert"],["Stones","Pierres"],["Medallions","Médaillons"],["Dungeon rewards","Récompenses"],["Dungeons","Donjons"],["Tokens","Symboles"],["Greg","Greg"]], def:"Vanilla" },
  { key:"bridgeStoneCount", soh:"Bridge Stone Count", label:"Pierres requises", card:"logic.wincon", type:'number', min:0, max:4, def:3, show:s => s.rainbowBridge === 'Stones' },
  { key:"bridgeMedallionCount", soh:"Bridge Medallion Count", label:"Médaillons requis", card:"logic.wincon", type:'number', min:0, max:7, def:6, show:s => s.rainbowBridge === 'Medallions' },
  { key:"bridgeRewardCount", soh:"Bridge Reward Count", label:"Récompenses requises", card:"logic.wincon", type:'number', min:0, max:10, def:9, show:s => s.rainbowBridge === 'Dungeon rewards' },
  { key:"bridgeDungeonCount", soh:"Bridge Dungeon Count", label:"Donjons requis", card:"logic.wincon", type:'number', min:0, max:9, def:8, show:s => s.rainbowBridge === 'Dungeons' },
  { key:"bridgeTokenCount", soh:"Bridge Token Count", label:"Symboles requis", card:"logic.wincon", type:'number', min:0, max:100, def:100, show:s => s.rainbowBridge === 'Tokens' },
  { key:"bridgeRewardOptions", soh:"Bridge Reward Options", label:"Greg (rubis vert) pour le pont", card:"logic.wincon", type:'choice', choices:[["Standard Rewards","Standard"],["Greg as Reward","Greg compte"],["Greg as Wildcard","Greg joker"]], def:"Standard Rewards", show:s => ['Stones','Medallions','Dungeon rewards','Dungeons'].includes(s.rainbowBridge) },
  { key:"ganonsTrials", soh:"Ganon's Trials", label:"Épreuves de Ganon", card:"logic.wincon", type:'choice', choices:[["Skip","Aucune"],["Set Number","Nombre fixe"],["Random Number","Nombre aléatoire"]], def:"Set Number" },
  { key:"ganonsTrialsCount", soh:"Ganon's Trials Count", label:"Nombre d'épreuves", card:"logic.wincon", type:'number', min:0, max:6, def:6, show:s => s.ganonsTrials === 'Set Number' },
  { key:"medallionLockedTrials", soh:"Medallion Locked Trials", label:"Épreuves verrouillées par médaillon", card:"logic.wincon", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off", show:s => s.ganonsTrials !== 'Skip' },
  { key:"triforceHunt", soh:"Triforce Hunt", label:"Chasse à la Triforce", card:"logic.wincon", type:'choice', choices:[["Off","Non"],["Win","Victoire"],["Ganon's Boss Key","Clé de Ganon"]], def:"Off" },
  { key:"triforceHuntTotal", soh:"Triforce Hunt Total Pieces", label:"Morceaux au total", card:"logic.wincon", type:'number', min:1, max:100, def:30, show:s => s.triforceHunt !== 'Off' },
  { key:"triforceHuntRequired", soh:"Triforce Hunt Required Pieces", label:"Morceaux requis", card:"logic.wincon", type:'number', min:1, max:100, def:20, show:s => s.triforceHunt !== 'Off' },
  { key:"skipChildStealth", soh:"Skip Child Stealth", label:"Passer l'infiltration du château", card:"logic.skips", type:'choice', choices:[["Don't Skip","Non"],["Skip","Oui"]], def:"Don't Skip" },
  { key:"skipChildZelda", soh:"Skip Child Zelda", label:"Passer la rencontre avec Zelda", card:"logic.skips", type:'choice', choices:[["Don't Skip","Non"],["Skip","Oui"]], def:"Don't Skip" },
  { key:"skipEponaRace", soh:"Skip Epona Race", label:"Passer la course d'Epona", card:"logic.skips", type:'choice', choices:[["Don't Skip","Non"],["Skip","Oui"]], def:"Don't Skip" },
  { key:"skipScarecrowsSong", soh:"Skip Scarecrow's Song", label:"Passer le chant de l'épouvantail", card:"logic.skips", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"skipPlantingBeans", soh:"Skip Planting Beans", label:"Haricots déjà plantés", card:"logic.skips", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"bigPoeTargetCount", soh:"Big Poe Target Count", label:"Gros Esprits à rapporter", card:"logic.skips", type:'number', min:0, max:10, def:10 },
  { key:"dungeonEntrances", soh:"Dungeon Entrances", label:"Donjons", card:"entrances.shuffle", type:'choice', choices:[["Off","Non"],["On","Oui"],["On + Ganon","Oui + Ganon"]], def:"Off" },
  { key:"bossEntrances", soh:"Boss Entrances", label:"Salles de boss", card:"entrances.shuffle", type:'choice', choices:[["Off","Non"],["Age Restricted","Par âge"],["Full","Complet"]], def:"Off" },
  { key:"ganonsTowerEntrance", soh:"Ganon's Tower Entrance", label:"Tour de Ganon", card:"entrances.shuffle", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off", show:s => s.bossEntrances !== 'Off' },
  { key:"overworldEntrances", soh:"Overworld Entrances", label:"Overworld", card:"entrances.shuffle", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"interiorEntrances", soh:"Interior Entrances", label:"Intérieurs", card:"entrances.shuffle", type:'choice', choices:[["Off","Non"],["Simple","Simples"],["All","Tous"]], def:"Off" },
  { key:"hideoutEntrances", soh:"Thieves' Hideout Entrances", label:"Repaire des Voleurs", card:"entrances.shuffle", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"grottoEntrances", soh:"Grottos Entrances", label:"Grottes et tombes", card:"entrances.shuffle", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"owlDrops", soh:"Owl Drops", label:"Hiboux", card:"entrances.oneway", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"warpSongs", soh:"Warp Songs", label:"Chants de téléportation", card:"entrances.oneway", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"overworldSpawns", soh:"Overworld Spawns", label:"Points d'apparition", card:"entrances.oneway", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"mixedEntrancePools", soh:"Mixed Entrance Pools", label:"Pools mélangés", card:"entrances.pools", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"mixDungeons", soh:"Mix Dungeons", label:"Mélanger les donjons", card:"entrances.pools", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off", show:s => s.mixedEntrancePools === 'On' && s.dungeonEntrances !== 'Off' },
  { key:"mixBosses", soh:"Mix Bosses", label:"Mélanger les boss", card:"entrances.pools", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off", show:s => s.mixedEntrancePools === 'On' && s.bossEntrances !== 'Off' },
  { key:"mixOverworld", soh:"Mix Overworld", label:"Mélanger l'overworld", card:"entrances.pools", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off", show:s => s.mixedEntrancePools === 'On' && s.overworldEntrances === 'On' },
  { key:"mixInteriors", soh:"Mix Interiors", label:"Mélanger les intérieurs", card:"entrances.pools", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off", show:s => s.mixedEntrancePools === 'On' && s.interiorEntrances !== 'Off' },
  { key:"mixThievesHideout", soh:"Mix Thieves' Hideout", label:"Mélanger le repaire", card:"entrances.pools", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off", show:s => s.mixedEntrancePools === 'On' && s.hideoutEntrances === 'On' },
  { key:"mixGrottos", soh:"Mix Grottos", label:"Mélanger les grottes", card:"entrances.pools", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off", show:s => s.mixedEntrancePools === 'On' && s.grottoEntrances === 'On' },
  { key:"decoupleEntrances", soh:"Decouple Entrances", label:"Entrées découplées", card:"entrances.pools", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"mapsCompasses", soh:"Maps/Compasses", label:"Cartes et boussoles", card:"dungeons.items", type:'choice', choices:[["Start With","Au départ"],["Vanilla","Vanilla"],["Own Dungeon","Son donjon"],["Any Dungeon","Tout donjon"],["Overworld","Overworld"],["Anywhere","Partout"]], def:"Own Dungeon" },
  { key:"smallKeys", soh:"Small Key Shuffle", label:"Petites clés", card:"dungeons.items", type:'choice', choices:[["Start With","Au départ"],["Vanilla","Vanilla"],["Own Dungeon","Son donjon"],["Any Dungeon","Tout donjon"],["Overworld","Overworld"],["Anywhere","Partout"]], def:"Own Dungeon" },
  { key:"gerudoFortressKeys", soh:"Gerudo Fortress Keys", label:"Clés de la Forteresse", card:"dungeons.items", type:'choice', choices:[["Vanilla","Vanilla"],["Any Dungeon","Tout donjon"],["Overworld","Overworld"],["Anywhere","Partout"]], def:"Vanilla", show:s => s.fortressCarpenters !== 'Free' },
  { key:"bossKeys", soh:"Boss Key Shuffle", label:"Clés de boss", card:"dungeons.items", type:'choice', choices:[["Start With","Au départ"],["Vanilla","Vanilla"],["Own Dungeon","Son donjon"],["Any Dungeon","Tout donjon"],["Overworld","Overworld"],["Anywhere","Partout"]], def:"Own Dungeon" },
  { key:"ganonsBossKey", soh:"Ganon's Boss Key", label:"Clé de Ganon", card:"dungeons.items", type:'choice', choices:[["Vanilla","Vanilla"],["Own Dungeon","Son donjon"],["Start With","Au départ"],["Any Dungeon","Tout donjon"],["Overworld","Overworld"],["Anywhere","Partout"],["LACS-Vanilla","LACS (vanilla)"],["LACS-Stones","LACS (pierres)"],["LACS-Medallions","LACS (médaillons)"],["LACS-Rewards","LACS (récompenses)"],["LACS-Dungeons","LACS (donjons)"],["LACS-Tokens","LACS (symboles)"],["100 GS Reward","Récompense 100 Skulltulas"]], def:"Vanilla" },
  { key:"gcbkStoneCount", soh:"GCBK Stone Count", label:"Pierres requises (clé de Ganon)", card:"dungeons.items", type:'number', min:0, max:4, def:3, show:s => s.ganonsBossKey === 'LACS-Stones' },
  { key:"gcbkMedallionCount", soh:"GCBK Medallion Count", label:"Médaillons requis (clé de Ganon)", card:"dungeons.items", type:'number', min:0, max:7, def:6, show:s => s.ganonsBossKey === 'LACS-Medallions' },
  { key:"gcbkRewardCount", soh:"GCBK Reward Count", label:"Récompenses requises (clé de Ganon)", card:"dungeons.items", type:'number', min:0, max:10, def:9, show:s => s.ganonsBossKey === 'LACS-Rewards' },
  { key:"gcbkDungeonCount", soh:"GCBK Dungeon Count", label:"Donjons requis (clé de Ganon)", card:"dungeons.items", type:'number', min:0, max:9, def:8, show:s => s.ganonsBossKey === 'LACS-Dungeons' },
  { key:"gcbkTokenCount", soh:"GCBK Token Count", label:"Symboles requis (clé de Ganon)", card:"dungeons.items", type:'number', min:0, max:100, def:100, show:s => s.ganonsBossKey === 'LACS-Tokens' },
  { key:"gcbkRewardOptions", soh:"GCBK LACS Reward Options", label:"Greg (rubis vert) pour la clé de Ganon", card:"dungeons.items", type:'choice', choices:[["Standard Reward","Standard"],["Greg as Reward","Greg compte"],["Greg as Wildcard","Greg joker"]], def:"Standard Reward", show:s => ['LACS-Stones','LACS-Medallions','LACS-Rewards','LACS-Dungeons'].includes(s.ganonsBossKey) },
  { key:"skeletonKey", soh:"Skeleton Key", label:"Clé squelette", card:"dungeons.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"dungeonRewards", soh:"Shuffle Dungeon Rewards", label:"Récompenses de donjon", card:"dungeons.rewards", type:'choice', choices:[["Vanilla","Vanilla"],["End of Dungeons","Fin des donjons"],["Any Dungeon","Tout donjon"],["Overworld","Overworld"],["Anywhere","Partout"]], def:"End of Dungeons" },
  { key:"linksPocket", soh:"Link's Pocket", label:"Poche de Link", card:"dungeons.rewards", type:'choice', choices:[["Dungeon Reward","Récompense"],["Advancement","Objet utile"],["Anything","N'importe quoi"],["Nothing","Rien"]], def:"Dungeon Reward" },
  { key:"linksPocketReward", soh:"Link's Pocket Reward Type", label:"Récompense dans la poche", card:"dungeons.rewards", type:'choice', choices:[["Dungeon Reward","Au choix"],["Stone","Pierre"],["Medallion","Médaillon"]], def:"Dungeon Reward", show:s => s.linksPocket === 'Dungeon Reward' },
  { key:"keyRings", soh:"Key Rings", label:"Trousseaux de clés", card:"dungeons.keyrings", type:'choice', choices:[["Off","Non"],["Random","Aléatoire"],["Count","Nombre"],["Selection","Sélection"]], def:"Off" },
  { key:"keyRingCount", soh:"Keyring Dungeon Count", label:"Nombre de trousseaux", card:"dungeons.keyrings", type:'number', min:0, max:9, def:8, show:s => s.keyRings === 'Count' },
  { key:"keyRingGerudoFortress", soh:"Gerudo Fortress Keyring", label:"Forteresse Gerudo", card:"dungeons.keyrings", type:'choice', choices:[["No","Non"],["Random","Aléatoire"],["Yes","Oui"]], def:"No", show:s => s.keyRings === 'Selection' },
  { key:"keyRingForestTemple", soh:"Forest Temple Keyring", label:"Temple de la Forêt", card:"dungeons.keyrings", type:'choice', choices:[["No","Non"],["Random","Aléatoire"],["Yes","Oui"]], def:"No", show:s => s.keyRings === 'Selection' },
  { key:"keyRingFireTemple", soh:"Fire Temple Keyring", label:"Temple du Feu", card:"dungeons.keyrings", type:'choice', choices:[["No","Non"],["Random","Aléatoire"],["Yes","Oui"]], def:"No", show:s => s.keyRings === 'Selection' },
  { key:"keyRingWaterTemple", soh:"Water Temple Keyring", label:"Temple de l'Eau", card:"dungeons.keyrings", type:'choice', choices:[["No","Non"],["Random","Aléatoire"],["Yes","Oui"]], def:"No", show:s => s.keyRings === 'Selection' },
  { key:"keyRingSpiritTemple", soh:"Spirit Temple Keyring", label:"Temple de l'Esprit", card:"dungeons.keyrings", type:'choice', choices:[["No","Non"],["Random","Aléatoire"],["Yes","Oui"]], def:"No", show:s => s.keyRings === 'Selection' },
  { key:"keyRingShadowTemple", soh:"Shadow Temple Keyring", label:"Temple de l'Ombre", card:"dungeons.keyrings", type:'choice', choices:[["No","Non"],["Random","Aléatoire"],["Yes","Oui"]], def:"No", show:s => s.keyRings === 'Selection' },
  { key:"keyRingBottomOfTheWell", soh:"Bottom of the Well Keyring", label:"Fond du Puits", card:"dungeons.keyrings", type:'choice', choices:[["No","Non"],["Random","Aléatoire"],["Yes","Oui"]], def:"No", show:s => s.keyRings === 'Selection' },
  { key:"keyRingGerudoTrainingGround", soh:"Gerudo Training Ground Keyring", label:"Gymnase Gerudo", card:"dungeons.keyrings", type:'choice', choices:[["No","Non"],["Random","Aléatoire"],["Yes","Oui"]], def:"No", show:s => s.keyRings === 'Selection' },
  { key:"keyRingGanonsCastle", soh:"Ganon's Castle Keyring", label:"Château de Ganon", card:"dungeons.keyrings", type:'choice', choices:[["No","Non"],["Random","Aléatoire"],["Yes","Oui"]], def:"No", show:s => s.keyRings === 'Selection' },
  { key:"mqDungeons", soh:"MQ Dungeon Setting", label:"Donjons Master Quest", card:"dungeons.mq", type:'choice', choices:[["None","Aucun"],["Set Number","Nombre fixe"],["Random","Aléatoire"],["Selection Only","Sélection"]], def:"None" },
  { key:"mqDungeonCount", soh:"MQ Dungeon Count", label:"Nombre de donjons MQ", card:"dungeons.mq", type:'number', min:0, max:12, def:0, show:s => s.mqDungeons === 'Set Number' },
  { key:"mqDungeonsSet", soh:"Set Dungeon Quests", label:"Imposer certains donjons", card:"dungeons.mq", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off", show:s => ['Set Number','Random'].includes(s.mqDungeons) },
  { key:"mqDekuTree", soh:"Deku Tree Quest", label:"Arbre Mojo", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"mqDodongosCavern", soh:"Dodongo's Cavern Quest", label:"Caverne Dodongo", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"mqJabuJabu", soh:"Jabu-Jabu's Belly Quest", label:"Ventre de Jabu-Jabu", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"mqForestTemple", soh:"Forest Temple Quest", label:"Temple de la Forêt", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"mqFireTemple", soh:"Fire Temple Quest", label:"Temple du Feu", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"mqWaterTemple", soh:"Water Temple Quest", label:"Temple de l'Eau", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"mqSpiritTemple", soh:"Spirit Temple Quest", label:"Temple de l'Esprit", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"mqShadowTemple", soh:"Shadow Temple Quest", label:"Temple de l'Ombre", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"mqBottomOfTheWell", soh:"Bottom of the Well Quest", label:"Fond du Puits", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"mqIceCavern", soh:"Ice Cavern Quest", label:"Caverne de Glace", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"mqGerudoTrainingGround", soh:"Gerudo Training Ground Quest", label:"Gymnase Gerudo", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"mqGanonsCastle", soh:"Ganon's Castle Quest", label:"Château de Ganon", card:"dungeons.mq", type:'choice', choices:[["Vanilla","Normal"],["Master Quest","MQ"],["Random","Aléatoire"]], def:"Vanilla", show:s => s.mqDungeons === 'Selection Only' || (['Set Number','Random'].includes(s.mqDungeons) && s.mqDungeonsSet === 'On') },
  { key:"shuffleSongs", soh:"Shuffle Songs", label:"Chants", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["Song Locations","Lieux de chants"],["Dungeon Rewards","Récompenses de donjon"],["Anywhere","Partout"]], def:"Song Locations" },
  { key:"shuffleTokens", soh:"Token Shuffle", label:"Symboles de Skulltula", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["Dungeons","Donjons"],["Overworld","Overworld"],["All Tokens","Partout"]], def:"Off" },
  { key:"shopsanity", soh:"Shop Shuffle", label:"Boutiques", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["Specific Count","Nombre fixe"],["Random","Aléatoire"]], def:"Off" },
  { key:"shopsanityCount", soh:"Shops Item Count", label:"Objets mélangés par boutique", card:"shuffles.locations", type:'number', min:0, max:7, def:0, show:s => s.shopsanity === 'Specific Count' },
  { key:"shuffleScrubs", soh:"Scrubs Shuffle", label:"Pestes Mojo", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["One-Time Only","Uniques"],["All","Tous"]], def:"Off" },
  { key:"shuffleMerchants", soh:"Shuffle Merchants", label:"Marchands", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["Bean Merchant Only","Haricots seuls"],["All But Beans","Sauf haricots"],["All","Tous"]], def:"Off" },
  { key:"shuffleBeehives", soh:"Shuffle Beehives", label:"Ruches", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleCows", soh:"Shuffle Cows", label:"Vaches", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shufflePots", soh:"Shuffle Pots", label:"Jarres", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["Dungeons","Donjons"],["Overworld","Overworld"],["All Pots","Partout"]], def:"Off" },
  { key:"shuffleGrass", soh:"Shuffle Grass", label:"Herbe", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["Dungeons","Donjons"],["Overworld","Overworld"],["All Grass","Partout"]], def:"Off" },
  { key:"shuffleCrates", soh:"Shuffle Crates", label:"Caisses", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["Dungeons","Donjons"],["Overworld","Overworld"],["All Crates","Partout"]], def:"Off" },
  { key:"shuffleTrees", soh:"Shuffle Trees", label:"Arbres", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleBushes", soh:"Shuffle Bushes", label:"Buissons", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleFreestanding", soh:"Shuffle Freestanding Items", label:"Objets au sol", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["Dungeons","Donjons"],["Overworld","Overworld"],["All Items","Partout"]], def:"Off" },
  { key:"shuffleFountainFairies", soh:"Shuffle Fairies in Fountains", label:"Fées des fontaines", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleStoneFairies", soh:"Shuffle Gossip Stone Fairies", label:"Fées des pierres à potins", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleBeanFairies", soh:"Shuffle Bean Fairies", label:"Fées des haricots", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleFairySpots", soh:"Shuffle Fairy Spots", label:"Cercles de fées", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"fishsanity", soh:"Fishsanity", label:"Pêche", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["Shuffle only Hyrule Loach","Loche seule"],["Shuffle Fishing Pond","Étang"],["Shuffle Overworld Fish","Poissons de l'overworld"],["Shuffle Both","Les deux"]], def:"Off" },
  { key:"fishsanityPondCount", soh:"Pond Fish Count", label:"Poissons de l'étang", card:"shuffles.locations", type:'number', min:0, max:17, def:0, show:s => ['Shuffle Fishing Pond','Shuffle Both'].includes(s.fishsanity) },
  { key:"fishsanityAgeSplit", soh:"Pond Age Split", label:"Poissons distincts par âge", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off", show:s => ['Shuffle Fishing Pond','Shuffle Both'].includes(s.fishsanity) },
  { key:"shuffleFrogSongRupees", soh:"Shuffle Frog Song Rupees", label:"Rubis des grenouilles", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleChestMinigame", soh:"Shuffle Chest Minigame", label:"Clés de la chasse au trésor", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On (Separate)","Séparées"],["On (Pack)","Trousseau"]], def:"Off" },
  { key:"shuffle100GsReward", soh:"Shuffle 100 GS Reward", label:"Récompense 100 Skulltulas", card:"shuffles.locations", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleKokiriSword", soh:"Shuffle Kokiri Sword", label:"Épée Kokiri", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleMasterSword", soh:"Shuffle Master Sword", label:"Épée de Légende", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleChildWallet", soh:"Shuffle Child's Wallet", label:"Bourse enfant", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"includeTycoonWallet", soh:"Include Tycoon Wallet", label:"Bourse de magnat", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleOcarinas", soh:"Shuffle Ocarinas", label:"Ocarinas", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleOcarinaButtons", soh:"Shuffle Ocarina Buttons", label:"Touches d'ocarina", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleWeirdEgg", soh:"Shuffle Weird Egg", label:"Œuf Bizarre", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleGerudoCard", soh:"Shuffle Gerudo Membership Card", label:"Carte Gerudo", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleAdultTrade", soh:"Shuffle Adult Trade", label:"Quête d'échange adulte", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"maskQuest", soh:"Mask Quest", label:"Quête des masques", card:"shuffles.items", type:'choice', choices:[["Vanilla","Vanilla"],["Completed","Terminée"],["Shuffle","Mélangée"]], def:"Vanilla" },
  { key:"shuffleFishingPole", soh:"Shuffle Fishing Pole", label:"Canne à pêche", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleStickBag", soh:"Shuffle Deku Stick Bag", label:"Sac de bâtons Mojo", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleNutBag", soh:"Shuffle Deku Nut Bag", label:"Sac de noix Mojo", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleBeanSouls", soh:"Shuffle Bean Souls", label:"Âmes de haricot", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleBossSouls", soh:"Shuffle Boss Souls", label:"Âmes de boss", card:"shuffles.items", type:'choice', choices:[["Off","Non"],["On","Oui"],["On + Ganon","Oui + Ganon"]], def:"Off" },
  { key:"shuffleSwim", soh:"Shuffle Swim", label:"Nager", card:"shuffles.abilities", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleClimb", soh:"Shuffle Climb", label:"Grimper", card:"shuffles.abilities", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleCrawl", soh:"Shuffle Crawl", label:"Ramper", card:"shuffles.abilities", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleGrab", soh:"Shuffle Grab", label:"Saisir", card:"shuffles.abilities", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleOpenChest", soh:"Shuffle Open Chest", label:"Ouvrir les coffres", card:"shuffles.abilities", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"shuffleJabberNuts", soh:"Shuffle Jabber Nuts", label:"Langues (noix Blabla)", card:"shuffles.abilities", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"bombchuBag", soh:"Bombchu Bag", label:"Sac de missiles", card:"shuffles.extras", type:'choice', choices:[["None","Aucun"],["Single Bag","Un sac"],["Progressive Bags","Progressif"]], def:"None" },
  { key:"bombchuDrops", soh:"Bombchu Drops", label:"Missiles à terre", card:"shuffles.extras", type:'choice', choices:[["No","Non"],["Yes","Oui"]], def:"Yes" },
  { key:"infiniteUpgrades", soh:"Infinite Upgrades", label:"Améliorations infinies", card:"shuffles.extras", type:'choice', choices:[["Off","Non"],["Progressive","Progressif"],["Condensed Progressive","Condensé"]], def:"Off" },
  { key:"blueFireArrows", soh:"Blue Fire Arrows", label:"Flèches de feu bleu", card:"shuffles.extras", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"sunlightArrows", soh:"Sunlight Arrows", label:"Flèches de lumière solaire", card:"shuffles.extras", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"rocsFeather", soh:"Roc's Feather", label:"Plume de Roc", card:"shuffles.extras", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"slingBowBeehives", soh:"Slingshot/Bow Can Break Beehives", label:"Lance-pierre et arc cassent les ruches", card:"shuffles.extras", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingOcarina", soh:"Start with Ocarina", label:"Ocarina", card:"starting.equipment", type:'choice', choices:[["Off","Non"],["Fairy Ocarina","Des Fées"],["Ocarina of Time","Du Temps"]], def:"Off" },
  { key:"startingDekuShield", soh:"Start with Deku Shield", label:"Bouclier Mojo", card:"starting.equipment", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingKokiriSword", soh:"Start with Kokiri Sword", label:"Épée Kokiri", card:"starting.equipment", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingMasterSword", soh:"Start with Master Sword", label:"Épée de Légende", card:"starting.equipment", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingSticks", soh:"Start with Stick Ammo", label:"Bâtons Mojo", card:"starting.equipment", type:'choice', choices:[["No","Non"],["Yes","Oui"]], def:"No" },
  { key:"startingNuts", soh:"Start with Nut Ammo", label:"Noix Mojo", card:"starting.equipment", type:'choice', choices:[["No","Non"],["Yes","Oui"]], def:"No" },
  { key:"startingBeans", soh:"Start with Magic Beans", label:"Haricots magiques", card:"starting.equipment", type:'choice', choices:[["No","Non"],["Yes","Oui"]], def:"No" },
  { key:"fullWallets", soh:"Full Wallets", label:"Bourses pleines", card:"starting.equipment", type:'choice', choices:[["No","Non"],["Yes","Oui"]], def:"No" },
  { key:"startingSkulltulaTokens", soh:"Gold Skulltula Tokens", label:"Symboles de Skulltula", card:"starting.equipment", type:'number', min:0, max:100, def:0 },
  { key:"startingHearts", soh:"Starting Hearts", label:"Cœurs", card:"starting.equipment", type:'number', min:1, max:20, def:3 },
  { key:"startingZeldasLullaby", soh:"Start with Zelda's Lullaby", label:"Berceuse de Zelda", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingEponasSong", soh:"Start with Epona's Song", label:"Chant d'Epona", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingSariasSong", soh:"Start with Saria's Song", label:"Chant de Saria", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingSunsSong", soh:"Start with Sun's Song", label:"Chant du Soleil", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingSongOfTime", soh:"Start with Song of Time", label:"Chant du Temps", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingSongOfStorms", soh:"Start with Song of Storms", label:"Chant des Tempêtes", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingMinuetOfForest", soh:"Start with Minuet of Forest", label:"Menuet des Bois", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingBoleroOfFire", soh:"Start with Bolero of Fire", label:"Boléro du Feu", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingSerenadeOfWater", soh:"Start with Serenade of Water", label:"Sérénade de l'Eau", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingRequiemOfSpirit", soh:"Start with Requiem of Spirit", label:"Requiem des Esprits", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingNocturneOfShadow", soh:"Start with Nocturne of Shadow", label:"Nocturne de l'Ombre", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
  { key:"startingPreludeOfLight", soh:"Start with Prelude of Light", label:"Prélude de la Lumière", card:"starting.songs", type:'choice', choices:[["Off","Non"],["On","Oui"]], def:"Off" },
];
const SETTING_BY_SOH = Object.fromEntries(SETTINGS_DEF.map(d => [d.soh, d]));
const settingVisible = (d, s) => !d.show || d.show(s);

// Options SoH volontairement ignorées (sans effet sur le suivi : prix, indices, pièges…).
const SETTINGS_IGNORED = new Set(["Shuffle Entrances","Shops Prices","Shops Fixed Price","Shops Lower Bound","Shops Upper Bound","Shops No Wallet Weight","Shops Child Wallet Weight","Shops Adult Wallet Weight","Shops Giant Wallet Weight","Shops Tycoon Wallet Weight","Shops Affordable Prices","Scrubs Prices","Scrubs Fixed Price","Scrubs Lower Bound","Scrubs Upper Bound","Scrubs No Wallet Weight","Scrubs Child Wallet Weight","Scrubs Adult Wallet Weight","Scrubs Giant Wallet Weight","Scrubs Tycoon Wallet Weight","Scrubs Affordable Prices","Merchant Prices","Merchant Fixed Price","Merchant Lower Bound","Merchant Upper Bound","Merchant No Wallet Weight","Merchant Child Wallet Weight","Merchant Adult Wallet Weight","Merchant Giant Wallet Weight","Merchant Tycoon Wallet Weight","Merchant Affordable Prices","Gossip Stone Hints","Hint Clarity","Hint Distribution","ToT Altar Hint","Ganondorf Hint","Sheik Light Arrow Hint","Boss Door Hints","Dampe's Diary Hint","Greg the Green Rupee Hint","Hyrule Loach Hint","Saria's Hint","Mido's Hint","Fishing Pole Hint","Frog Ocarina Game Hint","Ocarina of Time Hint","Biggoron's Hint","Big Poes Hint","Chickens Hint","Malon Hint","Horseback Archery Hint","Warp Song Hints","Scrub Hint Text","Merchant Hint Text","10 GS Hint","20 GS Hint","30 GS Hint","40 GS Hint","50 GS Hint","100 GS Hint","Mask Shop Hint","Item Pool","Base Ice Traps","Additional Ice Traps","Ice Trap Percent","All Locations Reachable","Damage Multiplier"]);

// Astuces de logique (193) : clé RT_*, nom SoH exact (celui des spoilers), zone, quête (BOTH/VANILLA/MQ), difficulté.
const TRICK_AREAS = {"NONE":"Général","KOKIRI_FOREST":"Forêt Kokiri","THE_LOST_WOODS":"Bois Perdus","HYRULE_CASTLE":"Château d'Hyrule","HYRULE_FIELD":"Plaine d'Hyrule","KAKARIKO_VILLAGE":"Village Cocorico","THE_GRAVEYARD":"Cimetière","DEATH_MOUNTAIN_TRAIL":"Chemin du Péril","GORON_CITY":"Village Goron","DEATH_MOUNTAIN_CRATER":"Cratère du Péril","ZORAS_RIVER":"Rivière Zora","ZORAS_DOMAIN":"Domaine Zora","ZORAS_FOUNTAIN":"Fontaine Zora","LAKE_HYLIA":"Lac Hylia","GERUDO_VALLEY":"Vallée Gerudo","GERUDO_FORTRESS":"Forteresse Gerudo","HAUNTED_WASTELAND":"Désert Hanté","DESERT_COLOSSUS":"Colosse du Désert","DEKU_TREE":"Arbre Mojo","DODONGOS_CAVERN":"Caverne Dodongo","JABU_JABUS_BELLY":"Ventre de Jabu-Jabu","BOTTOM_OF_THE_WELL":"Fond du Puits","FOREST_TEMPLE":"Temple de la Forêt","FIRE_TEMPLE":"Temple du Feu","WATER_TEMPLE":"Temple de l'Eau","SHADOW_TEMPLE":"Temple de l'Ombre","SPIRIT_TEMPLE":"Temple de l'Esprit","ICE_CAVERN":"Caverne de Glace","GERUDO_TRAINING_GROUND":"Gymnase Gerudo","GANONS_CASTLE":"Château de Ganon"};
const TRICK_LEVELS = { NOVICE:'Débutant', INTERMEDIATE:'Intermédiaire', ADVANCED:'Avancé', EXPERT:'Expert', EXTREME:'Extrême', GLITCH:'Bug', EXPERIMENTAL:'Expérimental' };
const TRICKS = [
  { key:"RT_VISIBLE_COLLISION", name:"Ignore Visible Collision", area:"NONE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_GROTTOS_WITHOUT_AGONY", name:"Hidden Grottos without Stone of Agony", area:"NONE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_FEWER_TUNIC_REQUIREMENTS", name:"Fewer Tunic Requirements", area:"NONE", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_UNINTUITIVE_JUMPS", name:"Unintuitive Jumps", area:"NONE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_FIRE_RINGS", name:"Fire Ring", area:"NONE", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_DAMAGE_BOOST_SIMPLE", name:"Simple damage boosts", area:"NONE", quest:"BOTH", tags:["ADVANCED","EXPERIMENTAL"] },
  { key:"RT_HOVER_BOOST_SIMPLE", name:"Simple hover boosts", area:"NONE", quest:"BOTH", tags:["ADVANCED","GLITCH"] },
  { key:"RT_BOMBCHU_BEEHIVES", name:"Bombchu Beehives", area:"NONE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_HOOKSHOT_LADDERS", name:"Hookshot Ladders", area:"NONE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_BLUE_FIRE_MUD_WALLS", name:"Blue Fire Beyond Red Ice", area:"NONE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_OPEN_UNDERWATER_CHEST", name:"Open Underwater Chests", area:"NONE", quest:"BOTH", tags:["NOVICE","GLITCH"] },
  { key:"RT_DISTANT_BOULDER_COLLISION", name:"Distant Boulder Collision", area:"NONE", quest:"BOTH", tags:["NOVICE","GLITCH"] },
  { key:"RT_ITEM_EXTENSION", name:"Item Extension", area:"NONE", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_BIG_SKULLTULA_PAUSE_LIFT", name:"Lift Big Skulltulas with Pausing", area:"NONE", quest:"BOTH", tags:["NOVICE","GLITCH"] },
  { key:"RT_GROUND_JUMP", name:"Ground Jump", area:"NONE", quest:"BOTH", tags:["NOVICE","GLITCH"] },
  { key:"RT_GROUND_JUMP_HARD", name:"Hard Ground Jumps", area:"NONE", quest:"BOTH", tags:["INTERMEDIATE","GLITCH"] },
  { key:"RT_SLIDE_JUMP", name:"Sliding Jumps", area:"NONE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_KF_ADULT_GS", name:"Adult Kokiri Forest GS with Hover Boots", area:"KOKIRI_FOREST", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_LW_BRIDGE", name:"Jump onto the Lost Woods Bridge as Adult with Nothing", area:"THE_LOST_WOODS", quest:"BOTH", tags:["EXPERT"] },
  { key:"RT_LW_MIDO_BACKFLIP", name:"Backflip over Mido as Adult", area:"THE_LOST_WOODS", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_LOST_WOOD_NAVI_DIVE", name:"Lost Woods Navi dive", area:"THE_LOST_WOODS", quest:"BOTH", tags:["NOVICE","GLITCH"] },
  { key:"RT_LW_GS_BEAN", name:"Lost Woods Adult GS without Bean", area:"THE_LOST_WOODS", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_HC_STORMS_GS", name:"Hyrule Castle Storms Grotto GS with Just Boomerang", area:"HYRULE_CASTLE", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_HF_BIG_POE_WITHOUT_EPONA", name:"Big Poe without Epona", area:"HYRULE_FIELD", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_KAK_TOWER_GS", name:"Kakariko Tower GS with Jumpslash", area:"KAKARIKO_VILLAGE", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_KAK_CHILD_WINDMILL_POH", name:"Windmill PoH as Child with Precise Jumpslash", area:"KAKARIKO_VILLAGE", quest:"BOTH", tags:["EXTREME"] },
  { key:"RT_KAK_ROOFTOP_GS", name:"Kakariko Rooftop GS with Hover Boots", area:"KAKARIKO_VILLAGE", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_GY_POH", name:"Graveyard Freestanding PoH with Boomerang", area:"THE_GRAVEYARD", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_GY_CHILD_DAMPE_RACE_POH", name:"Second Dampe Race as Child", area:"THE_GRAVEYARD", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_GY_SHADOW_FIRE_ARROWS", name:"Shadow Temple Entry with Fire Arrows", area:"THE_GRAVEYARD", quest:"BOTH", tags:["EXPERT"] },
  { key:"RT_DMT_SHIELDLESS_CLIMB", name:"Death Mountain Trail Child Climb Without Shield", area:"DEATH_MOUNTAIN_TRAIL", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_DMT_SOIL_GS", name:"Death Mountain Trail Soil GS without Destroying Boulder", area:"DEATH_MOUNTAIN_TRAIL", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_DMT_BOMBABLE", name:"Death Mountain Trail Chest with Strength", area:"DEATH_MOUNTAIN_TRAIL", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_DMT_HOVERS_LOWER_GS", name:"Death Mountain Trail Lower Red Rock GS with Hover Boots", area:"DEATH_MOUNTAIN_TRAIL", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_DMT_BEAN_LOWER_GS", name:"Death Mountain Trail Lower Red Rock GS with Magic Bean", area:"DEATH_MOUNTAIN_TRAIL", quest:"BOTH", tags:["EXPERT"] },
  { key:"RT_DMT_JS_LOWER_GS", name:"Death Mountain Trail Lower Red Rock GS with Jumpslash", area:"DEATH_MOUNTAIN_TRAIL", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_DMT_CLIMB_HOVERS", name:"Death Mountain Trail Climb with Hover Boots", area:"DEATH_MOUNTAIN_TRAIL", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_DMT_UPPER_GS", name:"Death Mountain Trail Upper Red Rock GS with Backflip", area:"DEATH_MOUNTAIN_TRAIL", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_GC_POT", name:"Goron City Spinning Pot PoH with Bombchu", area:"GORON_CITY", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_GC_POT_STRENGTH", name:"Goron City Spinning Pot PoH with Strength", area:"GORON_CITY", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_GC_ROLLING_STRENGTH", name:"Rolling Goron (Hot Rodder Goron) as Child with Strength", area:"GORON_CITY", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_GC_LEFTMOST", name:"Goron City Maze Left Chest with Hover Boots", area:"GORON_CITY", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_GC_GROTTO", name:"Goron City Grotto with Hookshot While Taking Damage", area:"GORON_CITY", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_GC_LINK_GORON_DINS", name:"Stop Link the Goron with Din's Fire", area:"GORON_CITY", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_DMC_HOVER_BEAN_POH", name:"Crater's Bean PoH with Hover Boots", area:"DEATH_MOUNTAIN_CRATER", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_DMC_BOLERO_JUMP", name:"Death Mountain Crater Jump to Bolero", area:"DEATH_MOUNTAIN_CRATER", quest:"BOTH", tags:["EXTREME"] },
  { key:"RT_DMC_BOULDER_JS", name:"Death Mountain Crater Upper to Lower with Hammer", area:"DEATH_MOUNTAIN_CRATER", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_DMC_BOULDER_SKIP", name:"Death Mountain Crater Upper to Lower Boulder Skip", area:"DEATH_MOUNTAIN_CRATER", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_ZR_LOWER", name:"Zora's River Lower Freestanding PoH as Adult with Nothing", area:"ZORAS_RIVER", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_ZR_UPPER", name:"Zora's River Upper Freestanding PoH as Adult with Nothing", area:"ZORAS_RIVER", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_ZR_HOVERS", name:"Zora's Domain Entry with Hover Boots", area:"ZORAS_RIVER", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_ZR_CUCCO", name:"Zora's Domain Entry with Cucco", area:"ZORAS_RIVER", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_ZD_KING_ZORA_SKIP", name:"Skip King Zora as Adult with Nothing", area:"ZORAS_DOMAIN", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_ZD_GS", name:"Zora's Domain GS with No Additional Items", area:"ZORAS_DOMAIN", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_ZF_GREAT_FAIRY_WITHOUT_EXPLOSIVES", name:"Zora's Fountain Great Fairy without Explosives", area:"ZORAS_FOUNTAIN", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_LH_LAB_WALL_GS", name:"Lake Hylia Lab Wall GS with Jumpslash", area:"LAKE_HYLIA", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_LH_LAB_DIVING", name:"Lake Hylia Lab Dive without Gold Scale", area:"LAKE_HYLIA", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_LH_WATER_HOOKSHOT", name:"Water Temple Entry without Iron Boots using Hookshot", area:"LAKE_HYLIA", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_GV_CRATE_HOVERS", name:"Gerudo Valley Crate PoH as Adult with Hover Boots", area:"GERUDO_VALLEY", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_GV_CHILD_TENT", name:"Gerudo Valley Enter Carpenter's Tent as Child", area:"GERUDO_VALLEY", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_GV_CHILD_CUCCO_JUMP", name:"Gerudo Valley Jump Fence with Cucco", area:"GERUDO_VALLEY", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_GV_HOOKSHOT_BRIDGE", name:"Gerudo Valley Bridge with only Hookshot", area:"GERUDO_VALLEY", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_PASS_GUARDS_WITH_NOTHING", name:"Sneak Past Moving Gerudo Guards with No Items", area:"GERUDO_FORTRESS", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_GF_WASTELAND_GATE_SIDEHOP_SKIP", name:"Gerudo's Fortress Gate Skip with Sidehop", area:"GERUDO_FORTRESS", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_GF_ADULT_SKIP_WASTELAND_GATE", name:"Gerudo's Fortress Skip Wasteland Gate as Adult", area:"GERUDO_FORTRESS", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_GF_WARRIOR_WITH_DIFFICULT_WEAPON", name:"Gerudo's Fortress Warriors with Difficult Weapons", area:"GERUDO_FORTRESS", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_GF_LEDGE_CLIP_INTO_GTG", name:"Ledge Clip into Training Ground", area:"GERUDO_FORTRESS", quest:"BOTH", tags:["NOVICE","GLITCH"] },
  { key:"RT_HW_CROSSING", name:"Wasteland Crossing without Hover Boots or Longshot", area:"HAUNTED_WASTELAND", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_LENS_HW", name:"Lensless Wasteland", area:"HAUNTED_WASTELAND", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_HW_REVERSE", name:"Reverse Wasteland", area:"HAUNTED_WASTELAND", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_COLOSSUS_GS", name:"Colossus Hill GS with Hookshot", area:"DESERT_COLOSSUS", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_DEKU_BASEMENT_GS", name:"Deku Tree Basement Vines GS with Jumpslash", area:"DEKU_TREE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_DEKU_B1_SKIP", name:"Deku Tree Basement without Slingshot", area:"DEKU_TREE", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_DEKU_B1_BOW_WEBS", name:"Deku Tree Basement Web to Gohma with Bow", area:"DEKU_TREE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_DEKU_B1_BACKFLIP_OVER_SPIKED_LOG", name:"Deku Tree Basement Backflip over Spiked Log", area:"DEKU_TREE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_DEKU_MQ_COMPASS_GS", name:"Deku Tree MQ Compass Room GS Boulders with Just Hammer", area:"DEKU_TREE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_DEKU_MQ_LOG", name:"Deku Tree MQ Roll Under the Spiked Log", area:"DEKU_TREE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_DC_SCARECROW_GS", name:"Dodongo's Cavern Scarecrow GS with Armos Statue", area:"DODONGOS_CAVERN", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_DC_VINES_GS", name:"Dodongo's Cavern Vines GS from Below with Longshot", area:"DODONGOS_CAVERN", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_DC_STAIRS_WITH_BOW", name:"Dodongo's Cavern Stairs with Bow", area:"DODONGOS_CAVERN", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_DC_SLINGSHOT_SKIP", name:"Dodongo's Cavern Child Slingshot Skips", area:"DODONGOS_CAVERN", quest:"VANILLA", tags:["EXPERT"] },
  { key:"RT_DC_SCRUB_ROOM", name:"Dodongo's Cavern Two Scrub Room with Strength", area:"DODONGOS_CAVERN", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_DC_HAMMER_FLOOR", name:"Dodongo's Cavern Smash the Boss Lobby Floor", area:"DODONGOS_CAVERN", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_DC_DODONGO_CHU", name:"Dodongo's Cavern Dodongo with Only Bombchus", area:"DODONGOS_CAVERN", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_DC_MQ_STAIRS_WITH_ONLY_STRENGTH", name:"Dodongo's Cavern MQ Stairs With Only Strength", area:"DODONGOS_CAVERN", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_DC_MQ_CHILD_BOMBS", name:"Dodongo's Cavern MQ Early Bomb Bag Area as Child", area:"DODONGOS_CAVERN", quest:"MQ", tags:["ADVANCED"] },
  { key:"RT_DC_MQ_CHILD_EYES", name:"Dodongo's Cavern MQ Light the Eyes with Strength as Child", area:"DODONGOS_CAVERN", quest:"MQ", tags:["EXPERT"] },
  { key:"RT_DC_MQ_ADULT_EYES", name:"Dodongo's Cavern MQ Light the Eyes with Strength as Adult", area:"DODONGOS_CAVERN", quest:"MQ", tags:["ADVANCED"] },
  { key:"RT_DC_EYES_CHU", name:"Dodongo's Cavern Light the Eyes with Bombchus", area:"DODONGOS_CAVERN", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_JABU_BOSS_HOVER", name:"Jabu Near Boss Room with Hover Boots", area:"JABU_JABUS_BELLY", quest:"VANILLA", tags:["INTERMEDIATE"] },
  { key:"RT_JABU_NEAR_BOSS_RANGED", name:"Jabu Near Boss Ceiling Switch/GS without Boomerang or Explosives", area:"JABU_JABUS_BELLY", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_JABU_NEAR_BOSS_EXPLOSIVES", name:"Jabu Near Boss Ceiling Switch with Explosives", area:"JABU_JABUS_BELLY", quest:"VANILLA", tags:["INTERMEDIATE"] },
  { key:"RT_JABU_B1_CUBE_HOVER", name:"Jabu B1 Pass Cube with Hover Boots", area:"JABU_JABUS_BELLY", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_LENS_JABU_MQ", name:"Jabu MQ without Lens of Truth", area:"JABU_JABUS_BELLY", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_JABU_MQ_RANG_JUMP", name:"Jabu MQ Compass Chest with Boomerang", area:"JABU_JABUS_BELLY", quest:"MQ", tags:["ADVANCED"] },
  { key:"RT_JABU_MQ_SOT_GS", name:"Jabu MQ Song of Time Block GS with Boomerang", area:"JABU_JABUS_BELLY", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_JABU_BARINADE_POTS", name:"Jabu Barinade with Pots", area:"JABU_JABUS_BELLY", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_LENS_BOTW", name:"Bottom of the Well without Lens of Truth", area:"BOTTOM_OF_THE_WELL", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_BOTTOM_OF_THE_WELL_NAVI_DIVE", name:"Bottom of the Well Navi dive", area:"BOTTOM_OF_THE_WELL", quest:"BOTH", tags:["NOVICE","GLITCH"] },
  { key:"RT_BOTW_CHILD_DEADHAND", name:"Child Dead Hand without Kokiri Sword", area:"BOTTOM_OF_THE_WELL", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_BOTW_BASEMENT", name:"Bottom of the Well Map Chest with Strength & Sticks", area:"BOTTOM_OF_THE_WELL", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_BOTW_PITS", name:"Bottom of the Well MQ Jump Over the Pits", area:"BOTTOM_OF_THE_WELL", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_BOTW_MQ_DEADHAND_KEY", name:"Bottom of the Well MQ Dead Hand Freestanding Key with Boomerang", area:"BOTTOM_OF_THE_WELL", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_FOREST_FIRST_GS", name:"Forest Temple First Room GS with Difficult-to-Use Weapons", area:"FOREST_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_FOREST_COURTYARD_EAST_GS", name:"Forest Temple East Courtyard GS with Boomerang", area:"FOREST_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_FOREST_VINES", name:"Forest Temple East Courtyard Vines with Hookshot", area:"FOREST_TEMPLE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_FOREST_COURTYARD_LEDGE", name:"Forest Temple NE Courtyard Ledge with Hover Boots", area:"FOREST_TEMPLE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_FOREST_DOORFRAME", name:"Forest Temple East Courtyard Door Frame with Hover Boots", area:"FOREST_TEMPLE", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_FOREST_OUTSIDE_BACKDOOR", name:"Forest Temple Outside Backdoor with Jumpslash", area:"FOREST_TEMPLE", quest:"BOTH", tags:["ADVANCED"] },
  { key:"RT_FOREST_COURTYARD_HEARTS_BOOMERANG", name:"Forest Temple Courtyard Hearts with Boomerang", area:"FOREST_TEMPLE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_FOREST_WELL_SWIM", name:"Swim Through Forest Temple Well with Hookshot", area:"FOREST_TEMPLE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_FOREST_MQ_BLOCK_PUZZLE", name:"Skip Forest Temple MQ Block Puzzle with Bombchu", area:"FOREST_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_FOREST_MQ_JS_HALLWAY_SWITCH", name:"Forest Temple MQ Twisted Hallway Switch with Jumpslash", area:"FOREST_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_FOREST_MQ_HOOKSHOT_HALLWAY_SWITCH", name:"Forest Temple MQ Twisted Hallway Switch with Hookshot", area:"FOREST_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_FOREST_MQ_RANG_HALLWAY_SWITCH", name:"Forest Temple MQ Twisted Hallway Switch with Boomerang", area:"FOREST_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_FOREST_MQ_CHILD_DOORFRAME", name:"Forest Temple MQ Doorframe GS as Child without Boomerang", area:"FOREST_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_FIRE_SOT", name:"Fire Temple Song of Time Room GS without Song of Time", area:"FIRE_TEMPLE", quest:"VANILLA", tags:["INTERMEDIATE"] },
  { key:"RT_FIRE_STRENGTH", name:"Fire Temple Climb without Strength", area:"FIRE_TEMPLE", quest:"VANILLA", tags:["INTERMEDIATE"] },
  { key:"RT_FIRE_SCARECROW", name:"Fire Temple East Tower without Scarecrow's Song", area:"FIRE_TEMPLE", quest:"VANILLA", tags:["EXPERT"] },
  { key:"RT_FIRE_SKIP_FLAME_WALLS", name:"Fire Temple Skip Flame Walls", area:"FIRE_TEMPLE", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_FIRE_MQ_NEAR_BOSS", name:"Fire Temple MQ Chest Near Boss without Breaking Crate", area:"FIRE_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_FIRE_MQ_BLOCKED_CHEST", name:"Fire Temple MQ Big Lava Room Blocked Door without Hookshot", area:"FIRE_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_FIRE_MQ_BK_CHEST", name:"Fire Temple MQ Boss Key Chest without Bow", area:"FIRE_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_FIRE_MQ_CLIMB", name:"Fire Temple MQ Climb without Fire Source", area:"FIRE_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_FIRE_MQ_MAZE_SIDE_ROOM", name:"Fire Temple MQ Lizalfos Maze Side Room without Box", area:"FIRE_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_FIRE_MQ_MAZE_HOVERS", name:"Fire Temple MQ Lower to Upper Lizalfos Maze with Hover Boots", area:"FIRE_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_FIRE_MQ_MAZE_JUMP", name:"Fire Temple MQ Lower to Upper Lizalfos Maze with Precise Jump", area:"FIRE_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_FIRE_MQ_ABOVE_MAZE_GS", name:"Fire Temple MQ Above Flame Wall Maze GS from Below with Longshot", area:"FIRE_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_WATER_LONGSHOT_TORCH", name:"Water Temple Torch Longshot", area:"WATER_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_WATER_CRACKED_WALL_HOVERS", name:"Water Temple Cracked Wall with Hover Boots", area:"WATER_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_WATER_CRACKED_WALL", name:"Water Temple Cracked Wall with No Additional Items", area:"WATER_TEMPLE", quest:"VANILLA", tags:["INTERMEDIATE"] },
  { key:"RT_WATER_BK_REGION", name:"Water Temple Boss Key Region with Hover Boots", area:"WATER_TEMPLE", quest:"VANILLA", tags:["INTERMEDIATE"] },
  { key:"RT_WATER_NORTH_BASEMENT_LEDGE_JUMP", name:"Water Temple North Basement Ledge with Precise Jump", area:"WATER_TEMPLE", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_WATER_FW_CENTRAL_GS", name:"Water Temple Central Pillar GS with Farore's Wind", area:"WATER_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_WATER_IRONS_CENTRAL_GS", name:"Water Temple Central Pillar GS with Iron Boots", area:"WATER_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_WATER_CENTRAL_BOW", name:"Water Temple Central Bow Target without Longshot or Hover Boots", area:"WATER_TEMPLE", quest:"VANILLA", tags:["ADVANCED"] },
  { key:"RT_WATER_HOOKSHOT_FALLING_PLATFORM_GS", name:"Water Temple Falling Platform Room GS with Hookshot", area:"WATER_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_WATER_RANG_FALLING_PLATFORM_GS", name:"Water Temple Falling Platform Room GS with Boomerang", area:"WATER_TEMPLE", quest:"VANILLA", tags:["INTERMEDIATE"] },
  { key:"RT_WATER_RIVER_GS", name:"Water Temple River GS without Iron Boots", area:"WATER_TEMPLE", quest:"VANILLA", tags:["INTERMEDIATE"] },
  { key:"RT_WATER_DRAGON_JUMP_DIVE", name:"Water Temple Dragon Statue Jump Dive", area:"WATER_TEMPLE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_WATER_ADULT_DRAGON", name:"Water Temple Dragon Statue Switch from Above the Water as Adult", area:"WATER_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_WATER_CHILD_DRAGON", name:"Water Temple Dragon Statue Switch from Above the Water as Child", area:"WATER_TEMPLE", quest:"VANILLA", tags:["ADVANCED"] },
  { key:"RT_WATER_MQ_CENTRAL_PILLAR", name:"Water Temple MQ Central Pillar with Fire Arrows", area:"WATER_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_WATER_IRON_BOOTS_LEDGE_GRAB", name:"Water Temple Ledge Grab While Surfacing with Iron Boots", area:"WATER_TEMPLE", quest:"BOTH", tags:["NOVICE","GLITCH"] },
  { key:"RT_WATER_INVISIBLE_HOOKSHOT_TARGET", name:"Water Temple Invisible Hookshot Target", area:"WATER_TEMPLE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_WATER_MORPHA_WITHOUT_HOOKSHOT", name:"Water Temple Morpha without Hookshot", area:"WATER_TEMPLE", quest:"BOTH", tags:["EXTREME"] },
  { key:"RT_LENS_SHADOW", name:"Shadow Temple Stationary Objects without Lens of Truth", area:"SHADOW_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_LENS_SHADOW_PLATFORM", name:"Shadow Temple Invisible Moving Platform without Lens of Truth", area:"SHADOW_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_LENS_BONGO", name:"Shadow Temple Bongo Bongo without Lens of Truth", area:"SHADOW_TEMPLE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_SHADOW_UMBRELLA_HOVER", name:"Shadow Temple Stone Umbrella Skip", area:"SHADOW_TEMPLE", quest:"BOTH", tags:["EXPERT"] },
  { key:"RT_SHADOW_UMBRELLA_CLIP", name:"Shadow Temple Stone Umbrella Clip", area:"SHADOW_TEMPLE", quest:"BOTH", tags:["NOVICE","GLITCH"] },
  { key:"RT_SHADOW_UMBRELLA_GS", name:"Shadow Temple Falling Spikes GS with Hover Boots", area:"SHADOW_TEMPLE", quest:"BOTH", tags:["EXPERT"] },
  { key:"RT_SHADOW_FREESTANDING_KEY", name:"Shadow Temple Freestanding Key with Bombchu", area:"SHADOW_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_SHADOW_STATUE", name:"Shadow Temple River Statue with Bombchu", area:"SHADOW_TEMPLE", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_SHADOW_BONGO", name:"Shadow Temple Bongo Bongo without projectiles", area:"SHADOW_TEMPLE", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_LENS_SHADOW_MQ", name:"Shadow Temple MQ Stationary Objects without Lens of Truth", area:"SHADOW_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_LENS_SHADOW_MQ_INVISIBLE_BLADES", name:"Shadow Temple MQ Invisible Blades Silver Rupees without Lens of Truth", area:"SHADOW_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_LENS_SHADOW_MQ_PLATFORM", name:"Shadow Temple MQ Invisible Moving Platform without Lens of Truth", area:"SHADOW_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_LENS_SHADOW_MQ_DEADHAND", name:"Shadow Temple MQ 2nd Dead Hand without Lens of Truth", area:"SHADOW_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_SHADOW_MQ_GAP", name:"Shadow Temple MQ Truth Spinner Gap with Longshot", area:"SHADOW_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_SHADOW_MQ_INVISIBLE_BLADES", name:"Shadow Temple MQ Invisible Blades without Song of Time", area:"SHADOW_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_SHADOW_MQ_HUGE_PIT", name:"Shadow Temple MQ Lower Huge Pit without Fire Source", area:"SHADOW_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_SHADOW_MQ_WINDY_WALKWAY", name:"Shadow Temple MQ Windy Walkway Reverse without Hover Boots", area:"SHADOW_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_LENS_SPIRIT", name:"Spirit Temple without Lens of Truth", area:"SPIRIT_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_SPIRIT_CHILD_CHU", name:"Spirit Temple Child Side Bridge with Bombchu", area:"SPIRIT_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_SPIRIT_WEST_LEDGE", name:"Spirit Temple Statue Room West Ledge Checks with Boomerang", area:"SPIRIT_TEMPLE", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_SPIRIT_LOWER_ADULT_SWITCH", name:"Spirit Temple Lower Adult Switch with Bombs", area:"SPIRIT_TEMPLE", quest:"VANILLA", tags:["ADVANCED"] },
  { key:"RT_SPIRIT_STATUE_JUMP", name:"Spirit Temple Statue Room Jump from Hands to Upper Ledges", area:"SPIRIT_TEMPLE", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_SPIRIT_MAP_CHEST", name:"Spirit Temple Map Chest with Bow", area:"SPIRIT_TEMPLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_SPIRIT_SUN_CHEST", name:"Spirit Temple Sun Block Room Chest with Bow", area:"SPIRIT_TEMPLE", quest:"VANILLA", tags:["ADVANCED"] },
  { key:"RT_SPIRIT_WALL", name:"Spirit Temple Shifting Wall with No Additional Items", area:"SPIRIT_TEMPLE", quest:"VANILLA", tags:["INTERMEDIATE"] },
  { key:"RT_LENS_SPIRIT_MQ", name:"Spirit Temple MQ without Lens of Truth", area:"SPIRIT_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_SPIRIT_MQ_SUN_BLOCK_SOT", name:"Spirit Temple MQ Sun Block Room as Child without Song of Time", area:"SPIRIT_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_SPIRIT_MQ_SUN_BLOCK_GS", name:"Spirit Temple MQ Sun Block Room GS with Boomerang", area:"SPIRIT_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_SPIRIT_MQ_LOWER_ADULT", name:"Spirit Temple MQ Lower Adult without Fire Arrows", area:"SPIRIT_TEMPLE", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_SPIRIT_MQ_FROZEN_EYE", name:"Spirit Temple MQ Frozen Eye Switch without Fire", area:"SPIRIT_TEMPLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_ICE_STALAGMITE_CLIP", name:"Ice Cavern Stalagmite Clips", area:"ICE_CAVERN", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_ICE_STALAGMITE_HOOKSHOT", name:"Ice Cavern Stalagmites with Hookshot", area:"ICE_CAVERN", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_ICE_BLOCK_GS", name:"Ice Cavern Block Room GS with Hover Boots", area:"ICE_CAVERN", quest:"VANILLA", tags:["INTERMEDIATE"] },
  { key:"RT_ICE_MQ_RED_ICE_GS", name:"Ice Cavern MQ Red Ice GS without Song of Time", area:"ICE_CAVERN", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_LENS_GTG", name:"Gerudo Training Ground without Lens of Truth", area:"GERUDO_TRAINING_GROUND", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_GTG_WITHOUT_HOOKSHOT", name:"Gerudo Training Ground Left Side Silver Rupees without Hookshot", area:"GERUDO_TRAINING_GROUND", quest:"VANILLA", tags:["INTERMEDIATE"] },
  { key:"RT_GTG_FAKE_WALL", name:"Reach Gerudo Training Ground Fake Wall Ledge with Hover Boots", area:"GERUDO_TRAINING_GROUND", quest:"BOTH", tags:["NOVICE"] },
  { key:"RT_GTG_LAVA_JUMP", name:"Gerudo Training Grounds Itemless Lava Room Jump", area:"GERUDO_TRAINING_GROUND", quest:"BOTH", tags:["INTERMEDIATE"] },
  { key:"RT_LENS_GTG_MQ", name:"Gerudo Training Ground MQ without Lens of Truth", area:"GERUDO_TRAINING_GROUND", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_GTG_MQ_WITH_HOOKSHOT", name:"Gerudo Training Ground MQ Left Side Silver Rupees with Hookshot", area:"GERUDO_TRAINING_GROUND", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_GTG_MQ_WITHOUT_HOOKSHOT", name:"Gerudo Training Ground MQ Left Side Silver Rupees without Hookshot", area:"GERUDO_TRAINING_GROUND", quest:"MQ", tags:["INTERMEDIATE"] },
  { key:"RT_LENS_GANON", name:"Ganon's Castle without Lens of Truth", area:"GANONS_CASTLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_GANON_SPIRIT_TRIAL_HOOKSHOT", name:"Spirit Trial without Hookshot", area:"GANONS_CASTLE", quest:"VANILLA", tags:["NOVICE"] },
  { key:"RT_LENS_GANON_MQ", name:"Ganon's Castle MQ without Lens of Truth", area:"GANONS_CASTLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_GANON_MQ_FIRE_TRIAL", name:"Fire Trial MQ with Hookshot", area:"GANONS_CASTLE", quest:"MQ", tags:["ADVANCED"] },
  { key:"RT_GANON_MQ_SHADOW_TRIAL", name:"Shadow Trial MQ Torch with Bow", area:"GANONS_CASTLE", quest:"MQ", tags:["NOVICE"] },
  { key:"RT_GANON_MQ_LIGHT_TRIAL", name:"Light Trial MQ without Hookshot", area:"GANONS_CASTLE", quest:"MQ", tags:["INTERMEDIATE"] },
];
const TRICK_BY_NAME = Object.fromEntries(TRICKS.map(t => [t.name, t]));
